### ISSUE TITLE
Re-define `Post_Metabox` using conventional  WordPress code

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#87]
## Problem

The `Post_Metabox` is currently defined using the `Queulat` package. 

https://github.com/creativecommons/creativecommons-base/blob/39e72523afed695b4934f5cb131b14182e684345/inc/metaboxes.php#L8

Since we have [established a consensus to deprecate the Queulat package](https://github.com/creativecommons/creativecommons-base/issues/69, we need to re-create the `Post_Metabox` using [conventional WordPress code](https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/).

## Task

- [ ] Determine what fields are needed for the `Post_Metabox`
- [ ] Determine how the metadata should be processed and stored
- [ ] Re-create the `Post_Metabox` using conventional WordPress code
- [ ] determine whether a more class-name meaningful name would be useful (if applicable)

**Comment by nox1134** [comment]
Hi @brylie ! I'd like to work on this issue?
